// Static SPA build for GitHub Pages.
// This is a PARALLEL build target — it does NOT replace the existing vite.config.ts
// (which targets Cloudflare Workers via @lovable.dev/vite-tanstack-config).
//
// Key differences from the Cloudflare build:
//  - No SSR / no Cloudflare plugin
//  - Plain client-side React SPA rendered into #root
//  - Outputs to dist-static/ instead of dist/
//  - All data fetching is already 100% client-side (Supabase), so no server needed
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";
import tsConfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [
    // NOTE: TanStackRouterVite is intentionally omitted here.
    // routeTree.gen.ts is already generated by the Cloudflare SSR build and is
    // imported as a regular TypeScript module — no regeneration needed.
    // Including the plugin would overwrite routeTree.gen.ts and strip out the
    // TanStack Start module augmentation declarations required by the SSR build.
    react(),
    tailwindcss(),
    tsConfigPaths(),
  ],
  // VITE_BASE_PATH=/upi-dashboard-redesign/  for github.io subdirectory
  // VITE_BASE_PATH=/                        for custom domain (default)
  base: process.env.VITE_BASE_PATH ?? "/",
  build: {
    outDir: "dist-static",
  },
});
