/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardYearRouteImport } from './routes/dashboard.year'
import { Route as DashboardSpendingRouteImport } from './routes/dashboard.spending'
import { Route as DashboardMilestonesRouteImport } from './routes/dashboard.milestones'
import { Route as DashboardDataRouteImport } from './routes/dashboard.data'
import { Route as DashboardCircularsIndexRouteImport } from './routes/dashboard.circulars.index'
import { Route as DashboardCircularsOcNumberRouteImport } from './routes/dashboard.circulars.$ocNumber'
import { Route as DashboardAppAppNameRouteImport } from './routes/dashboard.app.$appName'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardYearRoute = DashboardYearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSpendingRoute = DashboardSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMilestonesRoute = DashboardMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCircularsIndexRoute = DashboardCircularsIndexRouteImport.update({
  id: '/circulars/',
  path: '/circulars/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCircularsOcNumberRoute =
  DashboardCircularsOcNumberRouteImport.update({
    id: '/circulars/$ocNumber',
    path: '/circulars/$ocNumber',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppAppNameRoute = DashboardAppAppNameRouteImport.update({
  id: '/app/$appName',
  path: '/app/$appName',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/milestones': typeof DashboardMilestonesRoute
  '/dashboard/spending': typeof DashboardSpendingRoute
  '/dashboard/year': typeof DashboardYearRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/app/$appName': typeof DashboardAppAppNameRoute
  '/dashboard/circulars/$ocNumber': typeof DashboardCircularsOcNumberRoute
  '/dashboard/circulars/': typeof DashboardCircularsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/milestones': typeof DashboardMilestonesRoute
  '/dashboard/spending': typeof DashboardSpendingRoute
  '/dashboard/year': typeof DashboardYearRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/app/$appName': typeof DashboardAppAppNameRoute
  '/dashboard/circulars/$ocNumber': typeof DashboardCircularsOcNumberRoute
  '/dashboard/circulars': typeof DashboardCircularsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/milestones': typeof DashboardMilestonesRoute
  '/dashboard/spending': typeof DashboardSpendingRoute
  '/dashboard/year': typeof DashboardYearRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/app/$appName': typeof DashboardAppAppNameRoute
  '/dashboard/circulars/$ocNumber': typeof DashboardCircularsOcNumberRoute
  '/dashboard/circulars/': typeof DashboardCircularsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/data'
    | '/dashboard/milestones'
    | '/dashboard/spending'
    | '/dashboard/year'
    | '/dashboard/'
    | '/dashboard/app/$appName'
    | '/dashboard/circulars/$ocNumber'
    | '/dashboard/circulars/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/data'
    | '/dashboard/milestones'
    | '/dashboard/spending'
    | '/dashboard/year'
    | '/dashboard'
    | '/dashboard/app/$appName'
    | '/dashboard/circulars/$ocNumber'
    | '/dashboard/circulars'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/data'
    | '/dashboard/milestones'
    | '/dashboard/spending'
    | '/dashboard/year'
    | '/dashboard/'
    | '/dashboard/app/$appName'
    | '/dashboard/circulars/$ocNumber'
    | '/dashboard/circulars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/year': {
      id: '/dashboard/year'
      path: '/year'
      fullPath: '/dashboard/year'
      preLoaderRoute: typeof DashboardYearRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/spending': {
      id: '/dashboard/spending'
      path: '/spending'
      fullPath: '/dashboard/spending'
      preLoaderRoute: typeof DashboardSpendingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/milestones': {
      id: '/dashboard/milestones'
      path: '/milestones'
      fullPath: '/dashboard/milestones'
      preLoaderRoute: typeof DashboardMilestonesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/circulars/': {
      id: '/dashboard/circulars/'
      path: '/circulars'
      fullPath: '/dashboard/circulars/'
      preLoaderRoute: typeof DashboardCircularsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/circulars/$ocNumber': {
      id: '/dashboard/circulars/$ocNumber'
      path: '/circulars/$ocNumber'
      fullPath: '/dashboard/circulars/$ocNumber'
      preLoaderRoute: typeof DashboardCircularsOcNumberRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/app/$appName': {
      id: '/dashboard/app/$appName'
      path: '/app/$appName'
      fullPath: '/dashboard/app/$appName'
      preLoaderRoute: typeof DashboardAppAppNameRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardMilestonesRoute: typeof DashboardMilestonesRoute
  DashboardSpendingRoute: typeof DashboardSpendingRoute
  DashboardYearRoute: typeof DashboardYearRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppAppNameRoute: typeof DashboardAppAppNameRoute
  DashboardCircularsOcNumberRoute: typeof DashboardCircularsOcNumberRoute
  DashboardCircularsIndexRoute: typeof DashboardCircularsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDataRoute: DashboardDataRoute,
  DashboardMilestonesRoute: DashboardMilestonesRoute,
  DashboardSpendingRoute: DashboardSpendingRoute,
  DashboardYearRoute: DashboardYearRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppAppNameRoute: DashboardAppAppNameRoute,
  DashboardCircularsOcNumberRoute: DashboardCircularsOcNumberRoute,
  DashboardCircularsIndexRoute: DashboardCircularsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
