/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardYearRouteImport } from './routes/dashboard.year'
import { Route as DashboardTrendsRouteImport } from './routes/dashboard.trends'
import { Route as DashboardMilestonesRouteImport } from './routes/dashboard.milestones'
import { Route as DashboardDataRouteImport } from './routes/dashboard.data'
import { Route as DashboardContextRouteImport } from './routes/dashboard.context'
import { Route as DashboardAppAppNameRouteImport } from './routes/dashboard.app.$appName'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardYearRoute = DashboardYearRouteImport.update({
  id: '/year',
  path: '/year',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTrendsRoute = DashboardTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMilestonesRoute = DashboardMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContextRoute = DashboardContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppAppNameRoute = DashboardAppAppNameRouteImport.update({
  id: '/app/$appName',
  path: '/app/$appName',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/context': typeof DashboardContextRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/milestones': typeof DashboardMilestonesRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard/year': typeof DashboardYearRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/app/$appName': typeof DashboardAppAppNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/context': typeof DashboardContextRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/milestones': typeof DashboardMilestonesRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard/year': typeof DashboardYearRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/app/$appName': typeof DashboardAppAppNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/context': typeof DashboardContextRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/milestones': typeof DashboardMilestonesRoute
  '/dashboard/trends': typeof DashboardTrendsRoute
  '/dashboard/year': typeof DashboardYearRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/app/$appName': typeof DashboardAppAppNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/context'
    | '/dashboard/data'
    | '/dashboard/milestones'
    | '/dashboard/trends'
    | '/dashboard/year'
    | '/dashboard/'
    | '/dashboard/app/$appName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/context'
    | '/dashboard/data'
    | '/dashboard/milestones'
    | '/dashboard/trends'
    | '/dashboard/year'
    | '/dashboard'
    | '/dashboard/app/$appName'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/context'
    | '/dashboard/data'
    | '/dashboard/milestones'
    | '/dashboard/trends'
    | '/dashboard/year'
    | '/dashboard/'
    | '/dashboard/app/$appName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/year': {
      id: '/dashboard/year'
      path: '/year'
      fullPath: '/dashboard/year'
      preLoaderRoute: typeof DashboardYearRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trends': {
      id: '/dashboard/trends'
      path: '/trends'
      fullPath: '/dashboard/trends'
      preLoaderRoute: typeof DashboardTrendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/milestones': {
      id: '/dashboard/milestones'
      path: '/milestones'
      fullPath: '/dashboard/milestones'
      preLoaderRoute: typeof DashboardMilestonesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/context': {
      id: '/dashboard/context'
      path: '/context'
      fullPath: '/dashboard/context'
      preLoaderRoute: typeof DashboardContextRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/app/$appName': {
      id: '/dashboard/app/$appName'
      path: '/app/$appName'
      fullPath: '/dashboard/app/$appName'
      preLoaderRoute: typeof DashboardAppAppNameRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardContextRoute: typeof DashboardContextRoute
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardMilestonesRoute: typeof DashboardMilestonesRoute
  DashboardTrendsRoute: typeof DashboardTrendsRoute
  DashboardYearRoute: typeof DashboardYearRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAppAppNameRoute: typeof DashboardAppAppNameRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardContextRoute: DashboardContextRoute,
  DashboardDataRoute: DashboardDataRoute,
  DashboardMilestonesRoute: DashboardMilestonesRoute,
  DashboardTrendsRoute: DashboardTrendsRoute,
  DashboardYearRoute: DashboardYearRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAppAppNameRoute: DashboardAppAppNameRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
