-- Add logo_domain column to upi_apps
ALTER TABLE upi_apps ADD COLUMN IF NOT EXISTS logo_domain text;

-- Populate from curated domain map (covers all 125 apps)
UPDATE upi_apps SET logo_domain = CASE canonical_name
  -- Consumer apps
  WHEN 'PhonePe'                      THEN 'phonepe.com'
  WHEN 'Google Pay'                   THEN 'pay.google.com'
  WHEN 'Paytm'                        THEN 'paytm.com'
  WHEN 'Navi'                         THEN 'navi.com'
  WHEN 'super.money'                  THEN 'super.money'
  WHEN 'BHIM'                         THEN 'bhimupi.org.in'
  WHEN 'FamPay'                       THEN 'fampay.in'
  WHEN 'CRED'                         THEN 'cred.club'
  WHEN 'WhatsApp'                     THEN 'whatsapp.com'
  WHEN 'Amazon Pay'                   THEN 'amazon.in'
  WHEN 'MobiKwik'                     THEN 'mobikwik.com'
  WHEN 'Slice'                        THEN 'sliceit.com'
  WHEN 'Samsung Pay'                  THEN 'samsung.com'
  WHEN 'Groww'                        THEN 'groww.in'
  WHEN 'Bajaj Finserv'                THEN 'bajajfinserv.in'
  WHEN 'POP UPI'                      THEN 'popclub.in'
  WHEN 'Jupiter Money'                THEN 'jupiter.money'
  WHEN 'Ind Money'                    THEN 'indmoney.com'
  WHEN 'INDmoney'                     THEN 'indmoney.com'
  WHEN 'Money View'                   THEN 'moneyview.in'
  WHEN 'KreditBee'                    THEN 'kreditbee.in'
  WHEN 'Kiwi'                         THEN 'gokiwi.in'
  WHEN 'Flipkart'                     THEN 'flipkart.com'
  WHEN 'BharatPe'                     THEN 'bharatpe.com'
  WHEN 'OmniCard'                     THEN 'omnicard.in'
  WHEN 'Fi Money'                     THEN 'fi.money'
  WHEN 'Aditya Birla Capital Digital' THEN 'adityabirlacapital.com'
  WHEN 'Digikhata'                    THEN 'digikhata.in'
  WHEN 'Timepay'                      THEN 'timepay.in'
  WHEN 'Freo'                         THEN 'freo.money'
  WHEN 'Jar'                          THEN 'myjar.app'
  WHEN 'OneCard'                      THEN 'getonecard.app'
  WHEN 'Salary Se'                    THEN 'salaryse.com'
  WHEN 'Shriram One'                  THEN 'shriramone.in'
  WHEN 'RapiPay'                      THEN 'rapipay.com'
  WHEN 'Spice Money'                  THEN 'spicemoney.com'
  WHEN 'Saathi by PayNearBy'          THEN 'paynearby.in'
  WHEN 'Tata Neu'                     THEN 'tataneu.com'
  WHEN 'Obopay'                       THEN 'obopay.com'
  WHEN 'Dhani'                        THEN 'dhani.com'
  WHEN 'True Balance'                 THEN 'truebalance.io'
  WHEN 'TwidPay'                      THEN 'twid.in'
  WHEN 'Payworld'                     THEN 'payworld.in'
  WHEN 'Cheq'                         THEN 'cheq.one'
  WHEN 'Curie Money'                  THEN 'curie.money'
  WHEN 'Fave'                         THEN 'myfave.com'
  WHEN 'Ultracash'                    THEN 'ultracash.com'
  WHEN 'LXME'                         THEN 'lxme.in'
  WHEN 'ZET'                          THEN 'zet.in'
  WHEN 'Zomato'                       THEN 'zomato.com'
  WHEN 'MakeMyTrip'                   THEN 'makemytrip.com'
  WHEN 'Truecaller'                   THEN 'truecaller.com'
  WHEN 'Freecharge'                   THEN 'freecharge.in'
  WHEN 'GoIbibo'                      THEN 'goibibo.com'
  WHEN 'PineLabs'                     THEN 'pinelabs.com'
  WHEN 'Niyo Global'                  THEN 'niyo.co'
  WHEN 'Scapia'                       THEN 'scapia.in'
  -- Banks
  WHEN 'Axis Bank'                    THEN 'axisbank.com'
  WHEN 'Kotak Mahindra Bank'          THEN 'kotak.com'
  WHEN 'HDFC Bank'                    THEN 'hdfcbank.com'
  WHEN 'ICICI Bank'                   THEN 'icicibank.com'
  WHEN 'IDFC First Bank'              THEN 'idfcfirstbank.com'
  WHEN 'Yes Bank'                     THEN 'yesbank.in'
  WHEN 'India Post Payments Bank'     THEN 'ippbonline.com'
  WHEN 'Airtel Payments Bank'         THEN 'airtel.in'
  WHEN 'SBI'                          THEN 'onlinesbi.sbi'
  WHEN 'RBL Bank'                     THEN 'rblbank.com'
  WHEN 'Jio Payments Bank'            THEN 'jiopaymentsbank.com'
  WHEN 'Federal Bank'                 THEN 'federalbank.co.in'
  WHEN 'Deutsche Bank'                THEN 'db.com'
  WHEN 'Canara Bank'                  THEN 'canarabank.com'
  WHEN 'J&K Bank'                     THEN 'jkbank.com'
  WHEN 'Suryoday'                     THEN 'suryodaybank.com'
  WHEN 'Indian Bank'                  THEN 'indianbank.in'
  WHEN 'Bank of Baroda'               THEN 'bankofbaroda.in'
  WHEN 'Punjab National Bank'         THEN 'pnbindia.in'
  WHEN 'HSBC Bank'                    THEN 'hsbc.co.in'
  WHEN 'IndusInd Bank'                THEN 'indusind.com'
  WHEN 'Union Bank'                   THEN 'unionbankofindia.co.in'
  WHEN 'AU Small Finance Bank'        THEN 'aubank.in'
  WHEN 'South Indian Bank'            THEN 'southindianbank.com'
  WHEN 'Fino Payments Bank'           THEN 'finobank.com'
  WHEN 'UCO Bank'                     THEN 'ucobank.com'
  WHEN 'DBS Bank'                     THEN 'dbs.com'
  WHEN 'Standard Chartered Bank'      THEN 'sc.com'
  WHEN 'Central Bank of India'        THEN 'centralbankofindia.co.in'
  WHEN 'Bank of India'                THEN 'bankofindia.co.in'
  WHEN 'NSDL Payments Bank'           THEN 'nsdlbank.com'
  WHEN 'IDBI Bank'                    THEN 'idbibank.in'
  WHEN 'Karnataka Bank'               THEN 'karnatakabank.com'
  WHEN 'Karur Vysya Bank'             THEN 'kvb.co.in'
  WHEN 'Tamilnad Mercantile Bank'     THEN 'tmb.in'
  WHEN 'City Union Bank'              THEN 'cityunionbank.com'
  WHEN 'ESAF Small Finance Bank'      THEN 'esafbank.com'
  WHEN 'Indian Overseas Bank'         THEN 'iob.in'
  WHEN 'Bank of Maharashtra'          THEN 'bankofmaharashtra.in'
  WHEN 'Equitas Small Finance Bank'   THEN 'equitasbank.com'
  WHEN 'Unity Small Finance Bank'     THEN 'theunitybank.com'
  WHEN 'Punjab & Sind Bank'           THEN 'punjabandsindbank.co.in'
  WHEN 'Citi Bank'                    THEN 'citibank.co.in'
  WHEN 'Bandhan Bank'                 THEN 'bandhanbank.com'
  WHEN 'Bank of America'              THEN 'bankofamerica.com'
  WHEN 'Dhanlaxmi Bank'               THEN 'dhanbank.com'
  WHEN 'Utkarsh Small Finance Bank'   THEN 'utkarshbank.com'
  ELSE logo_domain
END;

-- Verify: how many apps now have a domain
SELECT
  COUNT(*) FILTER (WHERE logo_domain IS NOT NULL) AS with_domain,
  COUNT(*) FILTER (WHERE logo_domain IS NULL)     AS without_domain,
  COUNT(*)                                         AS total
FROM upi_apps;
